name: Auto Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'assets/**'
      - 'scripts/**'
      - 'src/**'

jobs:

  build_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Update APT
        run: sudo apt update

      - name: Cache HLS
        id: cache-hls
        uses: actions/cache@v4
        with:
          path: ./dist/hls
          key: hls-${{ hashFiles('assets/videos/**', 'scripts/build-hls.sh') }}

      - name: Install ffmpeg
        if: steps.cache-hls.outputs.cache-hit != 'true'
        run: sudo apt install -y ffmpeg

      - name: Install rclone and image conversion (x2)
        run: sudo apt install -y imagemagick rclone webp

      - name: Build static site
        run: ./scripts/build.sh

      - name: Deploy static site
        env:
          RCLONE_FTP_HOST: ${{ secrets.DEPLOY_HOST }}
          RCLONE_FTP_USER: ${{ secrets.DEPLOY_USER }}
          RCLONE_FTP_PASS: ${{ secrets.DEPLOY_PASS }}
        run: ./scripts/deploy.sh
